name: my-flask-app
deployment:
  image: python:3.10
  command:
    - gunicorn
    - main:app
    - --pythonpath
    - /app
    - --bind
    - 0.0.0.0:$PORT
  env: python
services:
  - name: app
    port: 3000
    command: python main.py
    healthCheckPath: /
  - name: db
    port: 3306
    internal: true
    disk: 100
    image: railway/mysql
    command: --default-authentication-plugin=mysql_native_password
